spring:
  application:
    name: demo
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://rm-cn-g4t4asx0u0009r0o.rwlb.rds.aliyuncs.com:5432/ai_agent_database_1
    username: my_user
  ai:
    vectorstore:
      pgvector:
      index-type: HNSW
      distance-type: COSINE_DISTANCE
      dimensions: 1536
      max-document-batch-size: 10000

server:
  port: 8123
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.kaisiaiagent.demo.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# youtube ducument reader config
youtube:
  video:
    url: ""